default_target: all
.PHONY : default_target


.NOTPARALLEL:





.SUFFIXES:


% : %,v


% : RCS/%


% : RCS/%,v


% : SCCS/s.%


% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list


$(VERBOSE)MAKESILENT = -s


$(VERBOSE).SILENT:


cmake_force:
.PHONY : cmake_force





SHELL = /bin/sh


CMAKE_COMMAND = /usr/bin/cmake


RM = /usr/bin/cmake -E rm -f


EQUALS = =


CMAKE_SOURCE_DIR = /home/zx/Documents/progi/lab2


CMAKE_BINARY_DIR = /home/zx/Documents/progi/lab2/build





edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache


edit_cache/fast: edit_cache
.PHONY : edit_cache/fast


rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache


rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast


all: cmake_check_build_system
	cd /home/zx/Documents/progi/lab2/build && $(CMAKE_COMMAND) -E cmake_progress_start /home/zx/Documents/progi/lab2/build/CMakeFiles /home/zx/Documents/progi/lab2/build/src//CMakeFiles/progress.marks
	cd /home/zx/Documents/progi/lab2/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zx/Documents/progi/lab2/build/CMakeFiles 0
.PHONY : all


clean:
	cd /home/zx/Documents/progi/lab2/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/clean
.PHONY : clean


clean/fast: clean
.PHONY : clean/fast


preinstall: all
	cd /home/zx/Documents/progi/lab2/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall


preinstall/fast:
	cd /home/zx/Documents/progi/lab2/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall/fast


depend:
	cd /home/zx/Documents/progi/lab2/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend


src/CMakeFiles/lab2_gtk.dir/rule:
	cd /home/zx/Documents/progi/lab2/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/CMakeFiles/lab2_gtk.dir/rule
.PHONY : src/CMakeFiles/lab2_gtk.dir/rule


lab2_gtk: src/CMakeFiles/lab2_gtk.dir/rule
.PHONY : lab2_gtk


lab2_gtk/fast:
	cd /home/zx/Documents/progi/lab2/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/lab2_gtk.dir/build.make src/CMakeFiles/lab2_gtk.dir/build
.PHONY : lab2_gtk/fast

main_gtk.o: main_gtk.cpp.o
.PHONY : main_gtk.o


main_gtk.cpp.o:
	cd /home/zx/Documents/progi/lab2/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/lab2_gtk.dir/build.make src/CMakeFiles/lab2_gtk.dir/main_gtk.cpp.o
.PHONY : main_gtk.cpp.o

main_gtk.i: main_gtk.cpp.i
.PHONY : main_gtk.i


main_gtk.cpp.i:
	cd /home/zx/Documents/progi/lab2/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/lab2_gtk.dir/build.make src/CMakeFiles/lab2_gtk.dir/main_gtk.cpp.i
.PHONY : main_gtk.cpp.i

main_gtk.s: main_gtk.cpp.s
.PHONY : main_gtk.s


main_gtk.cpp.s:
	cd /home/zx/Documents/progi/lab2/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/lab2_gtk.dir/build.make src/CMakeFiles/lab2_gtk.dir/main_gtk.cpp.s
.PHONY : main_gtk.cpp.s












cmake_check_build_system:
	cd /home/zx/Documents/progi/lab2/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

